
-- Tabela para armazenar os fechamentos individuais dos frentistas (via App Mobile)
create table if not exists public."FechamentoFrentista" (
    id bigint generated by default as identity primary key,
    fechamento_id bigint references public."Fechamento"(id) on delete cascade,
    frentista_id bigint references public."Frentista"(id),
    valor_cartao double precision default 0,
    valor_nota double precision default 0, 
    valor_pix double precision default 0,
    valor_dinheiro double precision default 0,
    valor_conferido double precision default 0,
    total double precision default 0,
    diferenca double precision default 0,
    observacoes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Políticas de segurança (RLS)
alter table public."FechamentoFrentista" enable row level security;

create policy "Permitir leitura para todos os autenticados"
on public."FechamentoFrentista" for select
to authenticated
using (true);

create policy "Permitir inserção para frentistas e gerentes"
on public."FechamentoFrentista" for insert
to authenticated
with check (true);

create policy "Permitir atualização para gerentes"
on public."FechamentoFrentista" for update
to authenticated
using (true);
