
-- Tabela de Convites para Criação de Usuários (Onboarding do App)
create table if not exists public."UserInvite" (
    id bigint generated by default as identity primary key,
    code text not null unique,
    email text not null,
    role "Role" not null default 'FRENTISTA',
    frentista_id bigint references public."Frentista"(id),
    status text default 'PENDENTE' check (status in ('PENDENTE', 'USADO', 'EXPIRADO')),
    created_by bigint references public."Usuario"(id),
    used_at timestamp with time zone,
    expires_at timestamp with time zone not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Adiciona campos na tabela Usuario para suporte ao App
alter table public."Usuario" 
add column if not exists frentista_id bigint references public."Frentista"(id),
add column if not exists avatar_url text,
add column if not exists push_token text,
add column if not exists device_info jsonb,
add column if not exists last_login_app timestamp with time zone;

-- Índices para performance
create index if not exists idx_user_invite_code on public."UserInvite"(code);
create index if not exists idx_usuario_frentista_id on public."Usuario"(frentista_id);

-- Políticas de Segurança (RLS) para UserInvite
alter table public."UserInvite" enable row level security;

create policy "Admins e Gerentes podem criar convites"
on public."UserInvite" for insert
to authenticated
with check (
    exists (
        select 1 from public."Usuario"
        where id = auth.uid() -- Ajustar se usar ID numérico mapeado, aqui assumindo auth.uid para simplificar ou custom logic
        and role in ('ADMIN', 'GERENTE')
    )
);

create policy "Qualquer um pode ler convite pelo código (para validação)"
on public."UserInvite" for select
to anon, authenticated
using (true);
